### ISSUE TITLE
No me aparece en mongo mi base de datos

### ISSUE THREAD

**Issue by NahuelM426** [groupbit/farmacias-turno#1]
![Captura de pantalla de 2019-07-08 20-34-59](https://user-images.githubusercontent.com/43456293/60849160-f69fbd00-a1bf-11e9-87b1-dabd89611e8e.png)
 
hice npm install en el fronten y el backend

**Comment by faloi** [comment]
¿Y guardaste algo? Porque la db se crea recién cuando guardás algún documento.

**Comment by NahuelM426** [comment]
Ahhhhh noo ahora lo hago gracias

**Comment by faloi** [comment]
Si con eso se arregla cerrá la issue. :smile:

**Comment by NahuelM426** [comment]
Hay encontré algo si no puedo te Mondo otra ves
